name: Baixar Imagem Docker

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permite rodar manualmente na aba Actions

jobs:
  pull-docker-image:
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o código do repositório (opcional, caso precise de arquivos locais)
    - name: Checkout do Código
      uses: actions/checkout@v4

    # 2. Configura o ambiente Docker no runner (já vem por padrão no ubuntu-latest)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3. Baixa (pull) a imagem Docker desejada
    - name: Baixar a Imagem Docker
      run: docker pull paulosilveira01/nginx:latest

